### ISSUE TITLE
FileNotFoundException when getting new token

### ISSUE THREAD

**Issue by zfc0812** [firemaples/microsoft-translator-java-api#1]
I got this error:
```
java.lang.Exception: [microsoft-translator-api] Error retrieving translation : https://api.cognitive.microsoft.com/sts/v1.0/issueToken
at io.github.firemaples.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:198)
at io.github.firemaples.translate.Translate.execute(Translate.java:63)
Caused by: java.io.FileNotFoundException: https://api.cognitive.microsoft.com/sts/v1.0/issueToken
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
at io.github.firemaples.MicrosoftTranslatorAPI.getToken(MicrosoftTranslatorAPI.java:130)
at io.github.firemaples.MicrosoftTranslatorAPI.retrieveResponse(MicrosoftTranslatorAPI.java:156)
at io.github.firemaples.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:195)
```

**Comment by zfc0812** [comment]
I think the reason why this happened is because I have exceeded the 2M character limit for the free package. Problem solved after I changed my subscription plan to paid one.
